name: Build and push docker image to the GitHub Container Registry
on:
  push:
    # Branch to be used in development
    branches:
      - main 
    paths-ignore:
      - 'README.md'
  
  # Triggered when a release is published
  release:
    types: [published]

  # workflow_dispatch can be used on feature branch to test the site
  # Or fix a bug on a release branch
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag (default: full commit hash)'
        required: false

jobs:
  push-to-container-registry:
    if: github.repository == 'ScilifelabDataCentre/omero-landing-page'  
    name: Build and push image to the GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            image_name: omero-landing-page
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Docker tag
        id: set-tag
        run: |
          ./set_docker_tag ${{ github.event_name }} \
                           ${{ github.ref_name }} \
                           ${{ github.sha }} \
                           ${{ github.event.inputs.docker_tag }} \
                           >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./docker/${{ matrix.dockerfile }}
          tags: |
            ghcr.io/scilifelabdatacentre/${{ matrix.image_name }}:${{ steps.set-tag.outputs.tag }}
            ghcr.io/scilifelabdatacentre/${{ matrix.image_name }}:latest
          build-args: |
            HUGO_ENV_ARG=${{ github.event_name == 'release' && format('{0}-{1}', 'production', github.ref_name)
                  || github.ref_name == 'main' && format('{0}-{1}', 'production', github.sha)
                  || format('{0}-{1}', 'development', github.sha) }}          